# Generated by Django 2.1.7 on 2019-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190311_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
