# Generated by Django 2.1.7 on 2019-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190311_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='menu'),
        ),
    ]
