# Generated by Django 2.1.7 on 2019-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='menu', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(verbose_name='Краткий рецепт'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Название блюда'),
        ),
    ]
