# Generated by Django 2.1.7 on 2019-03-12 13:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20190312_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='menu.Basket'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='Адресс Доставки (киоск)'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
