# Generated by Django 2.1.7 on 2019-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190312_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(default=None, max_length=225, null=True, verbose_name='Адрес Доставки (киоск)'),
        ),
    ]
